spring.application.name: width-board

spring:
  datasource:
#    url: ${db_url}
#    username: ${db_username}
#    password: ${db_password}
    url: jdbc:mysql://localhost:3306/withboard
    username: root
    password: wjd137928
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      hbm2ddl: auto=update
      ddl-auto: update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method