spring.application.name: width-board

spring:
  datasource:
    url: jdbc:mysql://database-1.c1iyqsw6eti1.ap-northeast-2.rds.amazonaws.com/withboard
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      hbm2ddl: auto=update
      ddl-auto: update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method